version: "2"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,module"
      standard: "Drupal"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true
exclude_patterns:
   - "docs/"
   - "examples/"
   - "mappings/"
   - "tests/"
   
