version: "2"
plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,module"
      standard: "Drupal"
  phpmd:
    enabled: true
    config:
      file_extensions: 
        - php
        - inc

exclude_patterns:
   - "docs/"
   - "examples/"
   - "mappings/"
   - "tests/"
   - "!includes/"
